#!/usr/bin/env python

"""
Simple test server to act as a local counterpart to the python tsclient. 
FOR TESTING ONLY!
"""

import sys
import socket

def hexstr(buf):
	respstr=""
	for c in buf:
	  respstr += "%.2x " % ord(c)
	return respstr

listen_port = 5556

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind(("", listen_port))
server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1) 
server_socket.listen(5)

print "\n\nTest server waiting port %d\n\n" % listen_port

try:
	try:
		while True:
			client_socket, address = server_socket.accept()
			cfile = client_socket.makefile("rw",0)
			data = cfile.readline().strip()
			print "%s (%d): RECEIVED %d bytes of data:\n%s" % (address[0],address[1],len(data),hexstr(data))
			print "   echo back: %s" % hexstr(data[1:7])
			cfile.write(data[1:7]) # Echo something back
			cfile.write("\n");
	except KeyboardInterrupt:
		# Break the loop on ctrl-c
		print >>sys.stdout, "\nServer terminating.\n\n";
	except Exception, err:
		print >>sys.stderr, "Exception: %s" % err
finally:
	server_socket.close()

